### ISSUE TITLE
unetbootin Quit Unexpectedly OSX Snow Leopard

### ISSUE THREAD

**Issue by theodorsudarja** [unetbootin/unetbootin#100]
unetbootin Quit Unexpectedly while opening the app.

Hardware: Macbook White 2006
OSX: Snow Leopard

I would try different version of unetbootin, if available. Where can I download previous version, or beta version of unetbootin?

![screen shot 2017-01-20 at 6 04 05 pm](https://cloud.githubusercontent.com/assets/557475/22147396/fcd760a0-df3a-11e6-8c71-ebad4a5fecdc.jpg)

**Comment by Brainzyy** [comment]
This is a dupe of: https://github.com/unetbootin/unetbootin/issues/73
You can download a different version here: https://launchpad.net/unetbootin/trunk/613/+download/unetbootin-mac-613.zip

**Comment by theodorsudarja** [comment]
Thx brainxyy
Solved
