### ISSUE TITLE
Parted Magic option does not work

### ISSUE THREAD

**Issue by TheLegoftheLambofGod** [unetbootin/unetbootin#101]
To recreate:
- Try create a new live boot disk with "Parted Magic" & "Latest_Live" as the options

unetbootin will try to download https://partedmagic.com/partedmagic-latest.iso which does not seem to exist.

Selecting the 2.1_Live option seems to work OK

The download page seems to show only paid for downloads
https://partedmagic.com/downloads/

**Comment by dmnc-net** [comment]
This option (Latest Live) has to be removed because Parted Magic can't be downloaded for free since 2013 ... http://www.phoronix.com/scan.php?page=news_item&px=MTQzNTI
