### ISSUE TITLE
Missing dependency on Xubuntu 14.04, not detected

### ISSUE THREAD

**Issue by Calinou** [unetbootin/unetbootin#11]
```
./unetbootin-linux-608.bin: error while loading shared libraries: libXrandr.so.2: cannot open shared object file: No such file or directory
```

I have `libxrandr-dev` and `libxrandr2` installed. Even putting libXrandr.so.2 in the same directory as UNetbootin won't work. `unetbootin-linux-585` also suffers from the same problem.

**Comment by gkovacs** [comment]
Issue is likely that you were running a 64-bit version of Xubuntu, but it's a 32-bit binary. On that version, installing the 32-bit version of libxrandr would have fixed the issue. Now, there is a 64-bit binary you can use - see http://unetbootin.sourceforge.net/unetbootin-linux64-latest - or you can install from the Ubuntu PPA ( https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa ). More instructions at https://unetbootin.github.io/linux_download.html
