### ISSUE TITLE
Executable Missing from MacOS DMG v638

### ISSUE THREAD

**Issue by marcusd687** [unetbootin/unetbootin#113]
Opening unetbootin-mac-638.dmg reveals an empty disk image with no executable to copy into the Applications folder.

**Comment by gkovacs** [comment]
Hrrm did you perhaps get a corrupted download? We are talking about the file at https://github.com/unetbootin/unetbootin/releases/download/638/unetbootin-mac-638.dmg right? Filesize should be 9.7M and running md5 should output:

```
geza@gezamac ~/Downloads> md5 unetbootin-mac-638.dmg
MD5 (unetbootin-mac-638.dmg) = 335ea18654106d50b0f0d6d23456d620
```
