### ISSUE TITLE
unetbootin can't understand of disks A and B

### ISSUE THREAD

**Issue by lutsch-mein-Glied** [unetbootin/unetbootin#114]
unetbootin under Windows can't understand that my disks A and B are not diskettes but they are usual flash usb drives.

**Comment by qwertychouskie** [comment]
What version of Windows?  It seems weird that Windows would assign letters A and B to flash drives, I've never seen this before.  It is generally understood by all programs that letters A and B always refer to floppy drives.

**Comment by lutsch-mein-Glied** [comment]
It was a laptop with Windows XP, but I think its OS version independent.
Surely it was not assigned by Windows - I did by myself. In the times we never will use floppy drives I always binding my usb sticks to A and B letters.
I have no proposals to change anything, just was curious about it and just would like you to know, a reporting.
Sincerely.

**Comment by gkovacs** [comment]
Make sure your drives are formatted as FAT32, then use the targetdrive option to force it to install to a particular drive. https://github.com/unetbootin/unetbootin/wiki/commands#targetdrive
