### ISSUE TITLE
Any ideas why I'm missing the file ui_unetbootin.h?

### ISSUE THREAD

**Issue by PellTheTabber1** [unetbootin/unetbootin#116]
I simply set my path to Qt5.6.2's bin dir where the lupate and lrelease commands are located.  I then ran lupdate, lrelease, and qmake (with the options recommended here), then when I ran make and it compiles main.cpp, it cannot find the file ui_unetbootin.h which is referenced in the file unetbootin.h (which it CAN find).  Should I actually be using Qt4?  I thought Qt5.6.2 would work since it's just another version of Qt4.  Any help appreciated while I look for the file ui_unetbootin.h.  Thanks.  Should I just add this as a FORMS += in the .pro file?  Funny (or NOT so funny), my unetbootin.pro file DOES have the line:
HEADERS += unetbootin.h
FORMS += unetbootin.ui
I tried just lupdate, lrelease, qmake, make (again no ui_unetbootin.h) which stops the build on error.

**Comment by gkovacs** [comment]
Yes, use qt4. See https://github.com/unetbootin/unetbootin/wiki/compile for instructions.

**Comment by PellTheTabber1** [comment]
Is there a trustworthy site of a source of some version of Qt4 that builds?  I have to build from source on my distro. I don't remember where I got my original Qt4, but Troll's doesn't build.  It errs differently on each version, and I'm tired of getting to the end with an error.  Even the configure's have files missing all the time.

**Comment by gkovacs** [comment]
I have some precompiled builds at https://github.com/unetbootin/unetbootin/wiki/compile#instructions-simple - if they don't work, you can always make clean and reconfigure

**Comment by gkovacs** [comment]
Also for reference I make the builds on debian 4 etch (for the 32-bit linux) or ubuntu 12.04 (for the 64-bit linux)

**Comment by PellTheTabber1** [comment]
It's rare that I take a chance on binaries, but I'll give it a try.  It might work on my distro.  If not, I'll eventually remember or find where I got my 5.6.? version.  One thing for sure - that version works really well so if they have an earlier one, I would probably be in good shape.  And that one had to be built.  But I'll try your way first.  It might save time.  I hope that the two versions on my machine do not conflict with each other - I haven't looked into that - I need both versions due to projects I've already built.  Thanks.

**Comment by PellTheTabber1** [comment]
I do not have 7zip.  I am trying to find a binary or source version that will work on my machine.  I wish I had binaries or source that were not 7zipped.  I am at the right website - I just have to pick one once I figure out which one is correct for my machine/Linux.

**Comment by gkovacs** [comment]
apt-get install p7zip or use a binary
