### ISSUE TITLE
Do not hardcode syslinux file paths (menu.c32, ...)

### ISSUE THREAD

**Issue by eMPee584** [unetbootin/unetbootin#12]
Various syslinux versions available in current distros use different paths.. something like

    else if (srcfName == "menu.c32")
    				srcF.setFileName(QFile::exists("/usr/share/syslinux/menu.c32") ? "/usr/share/syslinux/menu.c32" : "/usr/lib/syslinux/menu.c32");

is not working on various Debian/Ubuntu systems, probably others.. the relevant file might be
*/usr/lib/syslinux/modules/bios/menu.c32* with current syslinux versions..
 Please create a function to find these files in a somewhat more clever way - and display an error message if it can't be found, instead of silently producing unbootable USB sticks.

**Comment by gkovacs** [comment]
Should be fixed as of the latest release (613). Commit which fixed it was https://github.com/unetbootin/unetbootin/commit/d003b97265d5fb6066519f0cba275dd82132c01d
