### ISSUE TITLE
Can't format usb anymore

### ISSUE THREAD

**Issue by elmerehbi** [unetbootin/unetbootin#124]
I  used Unetbootin to make 2 persistent live usbs.

I wanted to format but I can't. I tried with Disks, mkfs, dd, but can't format. One of the usbs is no longer being recognized. Sometimes it keeps getting mounted and unmounted. And when  try to open the directory I get an IO error.

For the 1st one, the last thing I tried was

sudo dd if=/dev/zero of=/dev/sdc bs=4MB

When I mount it with Disks I can access a 2GB Loop device:
![16 gb thumb drive_014](https://cloud.githubusercontent.com/assets/3155152/26767836/c0dd651c-49a3-11e7-9a65-53376c728c69.png)
![2 0 gb loop device_016](https://cloud.githubusercontent.com/assets/3155152/26767838/c36adf62-49a3-11e7-9ac2-507569b5d2aa.png)

Here's the 2nd one which I can still access. I tried removing the Arch partition but it fails:
![selection_014](https://cloud.githubusercontent.com/assets/3155152/26767756/11106f6c-49a3-11e7-8a19-fd3dd044cf12.png)
![selection_015](https://cloud.githubusercontent.com/assets/3155152/26767759/1bd95aa8-49a3-11e7-9044-0be5d6f6f146.png)

How can I restore my usb drives?

PS: I am on Ubuntu Gnome 16.04 LTS

Thanks

**Comment by gkovacs** [comment]
strange, were you using dd or some tool other than unetbootin? unetbootin doesn't modify any of your partitions so it should not have caused this issue. anyhow use gparted to recreate the MBR on the flash drives, then create a new FAT32 partition that takes up the whole disk.

**Comment by elmerehbi** [comment]
@gkovacs I tried using MultiSystem in an attempt to overwrite it with another iso but neither usbs were detected by it so I didn't do anything.

And as I mentioned I tried "Disks" in Ubuntu as shown in the previous comment.

Gparted doesn' work either. It only detects a fraction of the usb. For example the 32GB shows as 1.89GB. I tried uploading an image but it's not working.

This is weird. It's not my first tie using either of these usbs or these tools I mentioned (except for dd maybe).

**Comment by rvanmil** [comment]
Same problem here. After using unetbootin the USB drive won't boot and it has become unusable. I'm unable to format it (tried on macOS, Windows and Linux, all fail).

**Comment by gkovacs** [comment]
looking at your screenshot I see the 2GB partition is iso9660. it would have been fat32 if you had been using unetbootin. so your issue was caused by using dd, not by unetbootin. I can see from the screenshot that it is indeed 32GB so the issue caused by dd is reversible. I'm pretty sure gparted should be able to fix the issue - as I said recreate the MBR first, then create new partitions - but if you don't manage to figure that out try reformatting the drive in windows.

**Comment by elmerehbi** [comment]
Thanks @gkovacs. I have managed to fix the 32 GB one.

@rvanmil  Here's how I did it. In gparted select the device from the list in the upper right corner. Then Select "Create Partition Table" under "Devices".
![-dev-sdc - gparted_014](https://user-images.githubusercontent.com/3155152/27016687-e61669da-4f22-11e7-9503-af0cc49493c4.png)

After that create a new partition (msdos) from Partition > New. It should cover the whole device by default. After that mine was working. Will confirm if the other one that shows up as 2GB works.

**Comment by rvanmil** [comment]
@elmerehbi thanks, I tried that. I guess my usb drive simply broke during the process, not related to this tool. I used a different one and that one is working properly.

**Comment by estelar9** [comment]
been struggling for the entire day on this, but you just h

**Comment by estelar9** [comment]
been struggling with this the whole day, turns out in /media/{username}/ there is the boot partition only accessible with root, Just delete everything inside, rebuild the partition table in gparted and you should regain full access to your usb key if it is not dead
