### ISSUE TITLE
Cannot find my .iso file

### ISSUE THREAD

**Issue by VortexIncAdmin** [unetbootin/unetbootin#136]
I downloaded UNetbootin and was about to install elementary OS from an .iso. But then I changed my mind and closed UNetbootin (It was not doing the process yet ;)). I grabbed a Linux Mint KDE 32-bit .iso, deleted the elementary OS .iso, and I reopened UNetbootin to get the .iso for Linux Mint. But aparrently... It was NOT in the UNetbootin open dialog! And it thought the elementary OS .iso was still available. I double checked the directory with the Linux Mint .iso and it WAS there! I refreshed the window, nothing! I got a new .exe, nothing! I did all I can do get this .iso working, and there is no solution. Any solutions? Also, I am running Windows 10.

**Comment by gkovacs** [comment]
Sounds like you're looking in the wrong directory for your linux mint iso file. It uses the standard windows file picker dialog so whatever you're seeing is the contents of your filesystem. Perhaps it's navigated to your recycle bin. Try navigating to the parent directory and digging down to your downloads directory from there, or try dragging-and-dropping the linux mint iso over onto the file picker dialog.
