### ISSUE TITLE
Use pkexec instead of gksu

### ISSUE THREAD

**Issue by qwertychouskie** [unetbootin/unetbootin#139]
`gksu` is depreciated now, and is not pre-installed in most distros nowadays.

I would just create a PR, except for this:
https://github.com/unetbootin/unetbootin/commit/b2cc79cd49c8508809dbf6aa6dce606cfbdaccf2
Why was this done?

**Comment by gkovacs** [comment]
yes I had implemented it and then I noticed in testing that the implementations of the pkexec command was broken/inconsistent on some major distributions at the time (I think it was some variants of either ubuntu or fedora) and then reverted back to using gksu/kdesu as a result. I'll check to see if the pkexec implementations are now working correctly on all major distributions

**Comment by breznak** [comment]
Can I bump this issue please? `gksu` has been removed from upcoming Debian and Ubuntu releases, so `pkexec` now must be working there correctly. 
Unetbootin is the only program that depends on gksu on my machine

https://jeremy.bicha.net/2018/03/21/gksu-is-dead/

**Comment by qwertychouskie** [comment]
This was fixed a while ago but never got closed, closing.
