### ISSUE TITLE
Make a check for Filesystem before Copying to USB

### ISSUE THREAD

**Issue by Wierd0n3** [unetbootin/unetbootin#15]
If the target filesystem is NTFS, Unetbootin will copy just fine, but at re-boot, you get a message "bootmgr not found" and lock you up. Please add a check to determine Fat32 or other supported FS

**Comment by gkovacs** [comment]
There is a check for FAT32, it won't even show the NTFS drives on the drop-down list of drives. I assume you were using the targetdrive command line option to bypass the FAT32 checks?

**Comment by divinity76** [comment]
unetbootin for windows, "unetbootin-windows-613.exe" internal version 1.1.1.1 listed my NTFS formatted drive, and installed xubuntu 14.03 on it without complaining.. ofc, i don't know any bios capable of booting this NTFS formatted USB

**Comment by divinity76** [comment]
@gkovacs it did for me.

**Comment by jwstolk** [comment]
I already entered a new issue, but I think it was the same as this one (using unetbootin-windows-657.exe)
My USB drive was listed, and only contained an NTFS partition.

**Comment by jhbruhn** [comment]
Please re-open this issue. This as not been resolved.
