### ISSUE TITLE
 Virus found in Unetbootin Jan 13 2018

### ISSUE THREAD

**Issue by egghead55425** [unetbootin/unetbootin#160]
Using Virustotal.com to scan unetbootin which I downloaded today from Sourceforge.net, the engine 'Tencent' found the virus called 'Suspicious.Heuristic.Gen.b.0'.

I advise you to not use Unetbootin until the virus is removed from the download.  I will also notify Sourceforge

**Comment by gkovacs** [comment]
This is a bug in your virus scanner. There is no virus. It probably just doesn't like that the executable is compressed with upx, this seems to cause some false positives in crappy antivirus software. Report the issue to your virus scanner company as a false positive.
