### ISSUE TITLE
Lost My Administrator Privilages After using this on windows 10.

### ISSUE THREAD

**Issue by badri-vishal** [unetbootin/unetbootin#169]
After using this software on windows i am unable to copy any kind of file to any USB device that is connected to PC, it shows "You need permission to perform this action" but i am already the administrator, i didn't create a system restore point on my PC . I can't seem to find any reliable solution for this error, i've seen plenty of youtube videos suggesting that i should install something like "Take Ownership" but they are not working . any other solutions besides re-installing windows on my system

thanks in advance

**Comment by qwertychouskie** [comment]
Not sure how Unetbootin could cause this... no idea what to do.  Use Linux ;)

**Comment by gkovacs** [comment]
this sounds like the user misattributed an issue caused by some other source to this software
