### ISSUE TITLE
Update unetbootin to 64-bit for Mac [Critical]

### ISSUE THREAD

**Issue by EdricChan03** [unetbootin/unetbootin#172]
Since Apple has decided that macOS High Sierra will be the last version to support 32-bit apps, unetbootin will probably not be able to run on future versions. I strongly suggest that this app be updated to 64-bit.

!["unetbootin" is not optimized for your Mac message](https://user-images.githubusercontent.com/20047125/38776541-15492568-40cb-11e8-820b-e199e0ac4d2a.jpg)

^ This is a one-time alert, as stated on [The Verge](https://www.theverge.com/2018/4/12/17228374/apple-macos-32-bit-app-alert)

**Comment by Russell-IO** [comment]
👍

**Comment by zadorozhko** [comment]
This happened. Unetbootin is not working under 10.14 Mojave.

**Comment by AlekSi** [comment]
It works for me on Mojave

**Comment by andrew-codechimp** [comment]
> It works for me on Mojave

It won't when the next release of Mojave (10.15) arrives, all 32 bit apps will stop working.

**Comment by EdricChan03** [comment]
@andrew-codechimp The next version of macOS is probably not going to be known as "Mojave" - that's for the current version of macOS.

**Comment by Syfaro** [comment]
As expected, it no longer works on macOS Catalina (10.15).

<img width="532" alt="Screen Shot 2019-06-05 at 3 40 09 PM" src="https://user-images.githubusercontent.com/1369709/58988868-35e58300-87a8-11e9-8bd3-b48095c053fd.png">

**Comment by mmuyskens** [comment]
+1 for 10.15 support.

**Comment by codercotton** [comment]
+1 for 10.15 support.

**Comment by EdricChan03** [comment]
@mmuyskens @codercotton No point adding your +1s to this issue- this just pings everyone who has watched this issue. Instead, add a thumbs up reaction on the original comment above.

**Comment by tieorange** [comment]
+1

**Comment by EdricChan03** [comment]
@tieorange Did you not read what I just commented?

**Comment by svu** [comment]
Highly critical. The days of 32-bit on Mac are numbered...

**Comment by InternalLoss** [comment]
Can confirm (obviously) that on macOS Catalina the app does not work, with the message that it requires updating; with the expected release of Catalina on the week of the 20th of September or so getting closer it'd be very helpful.

**Comment by pgrenaud** [comment]
macOS Catalina has been release yesterday and unetbootin has not been updated. 🙁

**Comment by cfrancesca46** [comment]
Please update to 64bit!

**Comment by EdricChan03** [comment]
Looks like a recent commit was added to allow for a 64-bit version of the app to be compiled: fca34afa7f325a659a89f3ed98d02ea86dd773e4

Release version [`675`](https://github.com/unetbootin/unetbootin/releases/tag/675) is also out which should fix the issue. As such, I'll close this issue.

**Comment by pgrenaud** [comment]
Thanks!
