### ISSUE TITLE
Unetbootin doesn't install in Ubuntu 18.04

### ISSUE THREAD

**Issue by shubhambhattar** [unetbootin/unetbootin#176]
It seems that Unetbootin depends on `gksu` which has been deprecated from Ubuntu 18.04. I also posted a question on AskUbuntu here: https://askubuntu.com/q/1030602/442336

**Comment by Skqnder** [comment]
@shubhambhattar that is only related to the PPA, you can still use Unetbootin binary. Refer to the answer I wrote on AskUbuntu for further details.

**Comment by qwertychouskie** [comment]
Now it is "only" a "Recommends:", so it can install, though the code itself needs to be fixed.  See https://github.com/unetbootin/unetbootin/issues/139.

**Comment by shubhambhattar** [comment]
Yes, I tried installing it after a few days with the same adding repo and it worked. Thanks @Skqnder @qwertychouskie
