### ISSUE TITLE
Blank GUI because of pkexec

### ISSUE THREAD

**Issue by MrksKwsnck** [unetbootin/unetbootin#177]
On my freshly installed Ubuntu 18.04 I installed UNetbootin from the official PPA.

When I run `unetbootin_asroot` the script runs until the line

``` bash
...
elif hash pkexec 2> /dev/null; then
pkexec unetbootin
else
...
```

without passing the needed environment variable

    QT_X11_NO_MITSHM=1

resulting in a blank GUI.

![grafik](https://user-images.githubusercontent.com/486983/40185144-35a1417a-59f2-11e8-8bc7-3b8cedb89829.png)

Unfortunately I don't have a clue how to pass environment variables to `pkexec` :-(

As a workaround I run UNetbootin with the following command

    sudo QT_X11_NO_MITSHM=1 /usr/bin/unetbootin

from the terminal.

![grafik](https://user-images.githubusercontent.com/486983/40185457-f15a38b8-59f2-11e8-93a0-7dadec927adc.png)

**Comment by qwertychouskie** [comment]
This should hopefully fix it: https://github.com/unetbootin/unetbootin/pull/179

**Comment by MrksKwsnck** [comment]
I can confirm this fix works perfectly. Thank you very much!

**Comment by Baltix** [comment]
@gkovacs Please update Ubuntu PPA packages (https://launchpad.net/~gezakovacs/+archive ) because unetbootin currently doesn't start in Ubuntu 18.04
Thanks
