### ISSUE TITLE
not working on fedora 28

### ISSUE THREAD

**Issue by khalil2535** [unetbootin/unetbootin#190]
Hello , i tried the last release (661) on fedora 28 workstation stable release and it's not working.
about my pc informations 
![screenshot from 2018-08-15 14-41-57](https://user-images.githubusercontent.com/26520106/44166467-75b47000-a099-11e8-9bd5-ac042beff887.png)

**Comment by uacode** [comment]
Hello, try this https://github.com/unetbootin/unetbootin/issues/94

**Comment by khalil2535** [comment]
@uacode That's what i did and worked fine ,but the issue is that new release has a bug that previous releases don't.
Thank's for your help.
