### ISSUE TITLE
PPA version: X Error: BadAccess (attempt to access private resource denied) 10

### ISSUE THREAD

**Issue by sanderjo** [unetbootin/unetbootin#194]
Ubuntu 18.04.

After installing unetbootin from PPA (`repository ppa:gezakovacs/ppa`), running unetbootin (as root) gives the error messages below, plus a grey window.

Tips how to solve this?

```
$ sudo unetbootin
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x146
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x380000f
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x3800010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x3800010
```

**Comment by sanderjo** [comment]
Ah, found workaround https://github.com/unetbootin/unetbootin/issues/66

```
sudo QT_X11_NO_MITSHM=1 unetbootin
```

which works on Ubuntu 18.04. 

But ... pity it is still a problem.

**Comment by tsvetiko** [comment]
For me this worked:

`export QT_GRAPHICSSYSTEM=native`

**Comment by dmbomer** [comment]
This workaround works in 18.04.3 kernel 5 when installing Natron installer using sudo.

**Comment by aogilvie** [comment]
This works for Fedora 32 as well.

```
# unetbootin-677-1.fc32.x86_6
sudo dnf install unetbootin

sudo QT_X11_NO_MITSHM=1 unetbootin
```

**Comment by Wth-Esp** [comment]
`sudo nano /etc/environment` and then add `QT_X11_NO_MITSHM=1` works for me under ubuntu 18.04.5 LTS. 
Thanks!

**Comment by sircollins** [comment]
Solution still works on Ubuntu 20.04.2 LTS. Worked for me after a fresh install of Ampps. Once again thanks

**Comment by cnlohr** [comment]
Any idea how one would actually fix this, or allow X to grant access? For instance, when I need MITSHM in QT?
