### ISSUE TITLE
Status of project - is it dead?

### ISSUE THREAD

**Issue by qwertychouskie** [unetbootin/unetbootin#200]
@gkovacs This project hasn't seen any activity in a very long time, the last commit was in April.  Is this project officially abandoned?  Maybe it's time for some of the members of the community to start maintaining the project?

Users are regularly opening/commenting on bug reports indicating that they are having issues (e.g. the infamous "must rename drive label to FAT32") that never get fixed.  Also, Unetbootin remains on QT4, which will probably threaten its inclusion in distro repositories soon.  And even small PRs like https://github.com/unetbootin/unetbootin.github.com/pull/7/files and https://github.com/unetbootin/unetbootin/pull/154 haven't been merged.

Maybe gave a few people collaborator permissions.  I don't have tons of free time on my hands, but if you gave collaborator permissions, maybe I could at least make some small bugfixes.

I'd hate to see Unetbootin completely die...
![](https://media.giphy.com/media/y9Tia8PxQMlhK/giphy.gif)

EDIT: Kinda funny that this is issue number 200

**Comment by gkovacs** [comment]
yes I am indeed somewhat occupied with other things, not officially abandoned, I have had other people ask for commit permissions and have given it to them but none really ended up making contributions or ended up creating tons of merge conflicts that made things harder for me, you're welcome to make pull requests though?

**Comment by macdaddy1944** [comment]
I am concerned that the Mac version is still 32-bit and will not work on Mac OS 10.15!

**Comment by gkovacs** [comment]
I've updated the macos version to be 64-bit as of the latest release (675)

**Comment by macdaddy1944** [comment]
Thank you so much. One more great app moving forward. 

==============================
Franklin Marder - 310-704-6903
macdaddy@macs4la.com
“Resistance is futile"

**Comment by macdaddy1944** [comment]
Tried to donate via PayPal and the amount is fixed at $0.00 with no way to modify.
==============================
Franklin Marder
Apple Certified Support Professional
macdaddy@macs4la.com

**Comment by gkovacs** [comment]
good catch! paypal annoyingly updated their interface breaking the old URLs, I've updated the link on https://unetbootin.github.io/ to https://www.paypal.me/gezak/10
