### ISSUE TITLE
fatal error: QtCore: No such file or directory  #include <QtCore>

### ISSUE THREAD

**Issue by KenyaLS** [unetbootin/unetbootin#218]
![Screenshot from 2019-04-28 15-33-33](https://user-images.githubusercontent.com/20774076/56863068-5bbe8180-69cb-11e9-8f14-eb90dcab0562.png)

Ubuntu 19.04 
debug g++  main.cpp

**Comment by gkovacs** [comment]
Please follow the compile instructions at  https://github.com/unetbootin/unetbootin/wiki/compile instead of attempting to use g++ dirrctly
