### ISSUE TITLE
Wont run in macOS Catalina (macOS 10.15)

### ISSUE THREAD

**Issue by alvileg** [unetbootin/unetbootin#223]
App won't run on this version of macOS

Maybe an early release to make it work?

**Comment by ipv6freely** [comment]
That's probably going to be a significant code re-write. Catalina will not run 32-bit apps - period. So, this would have to be re-written for 64-bit.

**Comment by gkovacs** [comment]
doesn't require a rewrite at all, just a recompile. I'll get around to it in a week or two

**Comment by codercotton** [comment]
+1 for 10.15 support.

**Comment by alvileg** [comment]
> doesn't require a rewrite at all, just a recompile. I'll get around to it in a week or two

It's been almost a month, any updates?

**Comment by areis422** [comment]
> > doesn't require a rewrite at all, just a recompile. I'll get around to it in a week or two
> 
> It's been almost a month, any updates?

Agreed. A recompile shouldn't take months, unless you ran into some build issues....?

**Comment by alvileg** [comment]
> doesn't require a rewrite at all, just a recompile. I'll get around to it in a week or two

2 months. xD Sorry for preasure, but it shouldn't take a while, as most people now are in vacation

**Comment by rwilliams** [comment]
I would love to see a 64 bit version as well

**Comment by gkovacs** [comment]
latest release (675) should now work in catalina

**Comment by XxUnkn0wnxX** [comment]
nope I just tested it runs osascript & just hangs after that application not responding.

**Comment by pirate** [comment]
Same here, latest release does not launch on Catalina 19A558d for me.

**Comment by martinbogo** [comment]
Confirmed ... same behavior on Catalina final.

**Comment by abhijithshaji** [comment]
Same issue, application not responding. Not even quitting

**Comment by stefan1983** [comment]
Same issue here as well

**Comment by mscheerer** [comment]
> doesn't require a rewrite at all, just a recompile. I'll get around to it in a week or two

Any update on the version for Catalina?

**Comment by codev0** [comment]
The same

**Comment by asheu321** [comment]
Same issue here

**Comment by sam0x17** [comment]
Same issue here on Catalina

**Comment by martinbogo** [comment]
Hey uNetBootin team...

I think we have plenty of "mee too's" on this bug.  I'm going to change the
tack -- what can I do to help debug and fix the situation?

Sincerely,
Martin

**Comment by jdbfsilva** [comment]
Just tried on Catalina, and I've got the same behaviour.

**Comment by gatopan** [comment]
Samesies

**Comment by blondie63** [comment]
same !

**Comment by kyczawon** [comment]
+1! :(

**Comment by martinbogo** [comment]
STOP with the +1's ... I think we have fully established there is a bug.
If you have debugging information or a potential fix please post it.

Otherwise, this does not have to be a "Mee too" thread.  It does not add
any technical value or move the bug forward.

**Comment by sam0x17** [comment]
@martinbogo yet the issue is still closed??

**Comment by rwilliams** [comment]
See https://github.com/unetbootin/unetbootin/issues/236 It's the new open issue for Catalina.

**Comment by bw-development** [comment]
Really +1:

**Comment by wyatt121** [comment]
@bw-development I tried your solution.  The window pops up, but when I press OK, nothing happens on screen, and this error is displayed within terminal:  "QPixmap::scaled: Pixmap is a null pixmap"

**Comment by tomas789** [comment]
@wyatt121 The @bw-development's solution worked for me. The window just did not pop up in front of the other windows. I had to dig it up.

**Comment by gemcosta** [comment]
@bw-development The terminal command also worked for me. For anyone else reading this, I first reformatted my USB drive with Disk Utility (exFAT, Master Boot Record).

I also didn't transfer the unetbootin.app into my applications folder, so my pathname was slightly different. Here's what got mine to work:
```
sudo /Volumes/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin method=diskimage isofile="/Users/yourusername/Desktop/Win10_1909_English_x64.iso" installtype=USB targetdrive=/dev/disk3
```

Terminal came back with an error ```QPixmap::scaled: Pixmap is a null pixmap``` but then I finally was able to see the GUI for netbootin, so I was able to click OK and get the process going.

Hope this helped another poor soul running Catalina trying to make a Windows 10 bootable USB.

**Comment by slan48** [comment]
> @bw-development The terminal command also worked for me. For anyone else reading this, I first reformatted my USB drive with Disk Utility (exFAT, Master Boot Record).
> 
> I also didn't transfer the unetbootin.app into my applications folder, so my pathname was slightly different. Here's what got mine to work:
> 
> ```
> sudo /Volumes/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin method=diskimage isofile="/Users/yourusername/Desktop/Win10_1909_English_x64.iso" installtype=USB targetdrive=/dev/disk3
> ```
> 
> Terminal came back with an error `QPixmap::scaled: Pixmap is a null pixmap` but then I finally was able to see the GUI for netbootin, so I was able to click OK and get the process going.
> 
> Hope this helped another poor soul running Catalina trying to make a Windows 10 bootable USB.

This is finally working!! Thanks for this tip!

**Comment by sanhue0302** [comment]
@bw-development I faced same issue. And your solution works for me. 
Will this issue be fixed in future release? since this issue has be closed?

**Comment by sam0x17** [comment]
Issue should be re-opened -- not sure why it was closed when no code was merged to resolve it.

**Comment by ryanissamson** [comment]
> @bw-development The terminal command also worked for me. For anyone else reading this, I first reformatted my USB drive with Disk Utility (exFAT, Master Boot Record).
> 
> I also didn't transfer the unetbootin.app into my applications folder, so my pathname was slightly different. Here's what got mine to work:
> 
> ```
> sudo /Volumes/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin method=diskimage isofile="/Users/yourusername/Desktop/Win10_1909_English_x64.iso" installtype=USB targetdrive=/dev/disk3
> ```
> 
> Terminal came back with an error `QPixmap::scaled: Pixmap is a null pixmap` but then I finally was able to see the GUI for netbootin, so I was able to click OK and get the process going.
> 
> Hope this helped another poor soul running Catalina trying to make a Windows 10 bootable USB.

This works all the way up until clicking "OK" at which point nothing happens. Why is this issue marked as closed?

**Comment by sam0x17** [comment]
To be fair, there are other more recent issues that also report this, but better to stick with the old issue and close new ones as duplicates imo

**Comment by scottlee120** [comment]
In case it helps someone, I discovered that the Ok button wasn't doing anything because I needed to manually select the right disk partition to write to - I had /disk2 and that wasn't working but when I switched to /disk2s2, Ok launched the process right away. 

All this was after launching through CLI as someone above noted btw.

**Comment by B3DTech** [comment]
Thank you!  For the love please fix this.  :)

**Comment by Haidertamsil98** [comment]
how to run this on high sierra ?

**Comment by Cyberdroid1** [comment]
Please reopen this issue. Still facing this issue.
@gemcosta 's method worked wonderfully, thanks!

**Comment by largestherb** [comment]
22nd of feb 2021 and still facing this issue on catalina. gemcosta's method is the saviour once again, though i had to sudo the command to get it to work.

**Comment by gixeco** [comment]
I've installed via homebrew, and on the first run it asked for the various permissions. Working fine, finally.
![image](https://user-images.githubusercontent.com/49438630/109003056-e000ef00-769e-11eb-9fa7-048d5669c471.png)

**Comment by Cyberdroid1** [comment]
Oh wow, I will give that a try surely.
