### ISSUE TITLE
Unetbootin does not install on OSX Catalina ( 10.5 )

### ISSUE THREAD

**Issue by martinbogo** [unetbootin/unetbootin#226]
Unetbootin does not install on OSX Catalina ( 10.5 Beta 19A501i ) 

![Screen Shot 2019-07-09 at 3 12 02 PM](https://user-images.githubusercontent.com/251177/60919689-f94ff000-a25b-11e9-86e9-0e14a78d64f2.png)
![Screen Shot 2019-07-09 at 3 11 47 PM](https://user-images.githubusercontent.com/251177/60919690-f9e88680-a25b-11e9-8285-2198bc04bd16.png)
![Screen Shot 2019-07-09 at 3 11 38 PM](https://user-images.githubusercontent.com/251177/60919691-f9e88680-a25b-11e9-9e11-1a4f204eb52a.png)

**Comment by adonix-dev** [comment]
Yes it does not instal ...

**Comment by xlint** [comment]
me too

**Comment by ssx** [comment]
It's not running because its a 23bit application. Are there any plans for a 64bit version?

**Comment by gkovacs** [comment]
latest release (675) should now work in catalina
