### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by hesco** [unetbootin/unetbootin#231]
I get the same sort of issues whether building from HEAD of master or checking out tag 631.  

-- Hugh 

hesco@marcus012:/opt/unetbootin/src/unetbootin/src/unetbootin$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I. -o main.o main.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I. -o unetbootin.o unetbootin.cpp
unetbootin.cpp:3727:2: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
  "\nmenuentry \""UNETBOOTINB"\" {\n"
  ^
unetbootin.cpp:3848:2: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
  "\ntitle "UNETBOOTINB"\n"
  ^
unetbootin.cpp:4346:29: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   rebootmsgtext->setText(tr("After rebooting, select the "UNETBOOTINB" menu entry to boot.%1").arg(postinstmsg));
                             ^
unetbootin.cpp: In member function ‘void unetbootin::on_typeselect_currentIndexChanged(int)’:
unetbootin.cpp:703:56: warning: unused parameter ‘typeselectIndex’ [-Wunused-parameter]
 void unetbootin::on_typeselect_currentIndexChanged(int typeselectIndex)
                                                        ^~~~~~~~~~~~~~~
unetbootin.cpp: In member function ‘void unetbootin::logText(const QString&)’:
unetbootin.cpp:4051:41: warning: unused parameter ‘text’ [-Wunused-parameter]
 void unetbootin::logText(const QString &text)
                                         ^~~~
g++ -m64 -Wl,-O1 -o unetbootin main.o unetbootin.o moc_unetbootin.o    -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread

**Comment by gkovacs** [comment]
oh some kind soul fixed this in a pull request https://github.com/unetbootin/unetbootin/pull/219 latest release (675) should compile without issues hopefully
