### ISSUE TITLE
MacOS Catalina

### ISSUE THREAD

**Issue by ManoLoko** [unetbootin/unetbootin#241]
unetbootin doesn't open on macos Catalina. the application does not respond.

**Comment by royimous** [comment]
Catalina really messed up a bunch of things, didn't it?

balenaEtcher had a similar issue after updating. I just tried what I did for Etcher and it managed to get unetbootin to start up. 

Open terminal and enter the following:
`sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin`

And it opens! I haven't tested to see if it works properly though. Wish me luck.

<img width="1198" alt="Screenshot 2019-11-07 02 10 15" src="https://user-images.githubusercontent.com/1146050/68367464-c8959f80-0103-11ea-8051-ed453c320c57.png">

**Comment by royimous** [comment]
Update: It works! I was able to set up Kali Linux on my USB drive.

**Comment by Githubsuckssomuchdick** [comment]
This doesn't work for me.   Tried to run via Terminal and it asks for password but doesn't let me type or paste one into it.

**Comment by royimous** [comment]
> This doesn't work for me. Tried to run via Terminal and it says command not found.

Works for me in Terminal. `sudo` is a standard command so you probably have a typo somewhere. I just tried it again and it works.

**Comment by rezahussain** [comment]
Doesn't work for me on Catalina 10.15.1, Application not responding

**Comment by diver-down** [comment]
Just chiming-in to help confirm the problem:  unetbootin isn't operable on Catalina 10.15.1 (19B88). A sudo terminal launch seems to do the trick.

**Comment by airspeed** [comment]
Related to this issue? https://developer.apple.com/news/?id=10032019a

**Comment by twogee** [comment]
It works with sudo from CLI on 10.15.1, but spits out errors `QPixmap::scaled: Pixmap is a null pixmap`; caused a missing image? Also, please consider upgrading to Qt 5 for High DPI support.

**Comment by phonggenix** [comment]
> sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin
works for me. MacOS Catalina 10.15.1.

**Comment by awebling** [comment]
> It works with sudo from CLI on 10.15.1, but spits out errors `QPixmap::scaled: Pixmap is a null pixmap`; caused a missing image? Also, please consider upgrading to Qt 5 for High DPI support.

Same for me

**Comment by TyrannosaurHex** [comment]
> It works with sudo from CLI on 10.15.1, but spits out errors `QPixmap::scaled: Pixmap is a null pixmap`; caused by a missing image? Also, please consider upgrading to Qt 5 for High DPI support.

Getting the same error on Catalina.

**Comment by crup** [comment]
> > It works with sudo from CLI on 10.15.1, but spits out errors `QPixmap::scaled: Pixmap is a null pixmap`; caused by a missing image? Also, please consider upgrading to Qt 5 for High DPI support.
> 
> Getting the same error on Catalina.

Same for me but it opens up app in dock, you can use app by clicking on that icon.

**Comment by MatteoSid** [comment]
> Catalina really messed up a bunch of things, didn't it?
> 
> balenaEtcher had a similar issue after updating. I just tried what I did for Etcher and it managed to get unetbootin to start up.
> 
> Open terminal and enter the following:
> `sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin`
> 
> And it opens! I haven't tested to see if it works properly though. Wish me luck.
> 
> <img alt="Screenshot 2019-11-07 02 10 15" width="1198" src="https://user-images.githubusercontent.com/1146050/68367464-c8959f80-0103-11ea-8051-ed453c320c57.png">

I had the same problem, thanks for the solution.

**Comment by jfha73** [comment]
I'm trying running it like that, but all I get is:

QPixmap::scaled: Pixmap is a null pixmap

And nothing shows up, I'm using Catalina 10.15.1 on a MacPro from Late 2013

Any ideas?

**Comment by gkovacs** [comment]
catalina should now work correctly with release 377, please report issues if you still encounter them

**Comment by phenomeus** [comment]
not working, while trying to select the Drive: its constantly saying: Pixmap is a null pixmap

no list comes up to select the right drive

**Comment by gkovacs** [comment]
@phenomeus format the drive as FAT32, only FAT32 formatted drives are supported

**Comment by phenomeus** [comment]
I did of course, with gpt and even mbr

**Comment by gkovacs** [comment]
Please post the output of running the following command in the terminal:

diskutil list

phenomeus <notifications@github.com> 于 2020年1月30日周四 02:18写道：

**Comment by gkovacs** [comment]
(run "diskutil list" with the USB drive plugged in)

Geza Kovacs <geza0kovacs@gmail.com> 于 2020年1月30日周四 11:03写道：

**Comment by phenomeus** [comment]
sorry, I'm done and went on with solving my actual problems. will come back later when I need a bootable linux live usb
