### ISSUE TITLE
Osascript macOS Catalina

### ISSUE THREAD

**Issue by floyernick** [unetbootin/unetbootin#248]
What UNetbootin is trying to load with Osascript on Mac using additional privileges? I'm really concerned on the security of this tool. Where can I see the script that it runs? How can I rollback changes made by it if I stopped script (it just doesn't respond)? And yes, it hasn't installed anything visible. Just non-responding process.

Version is 675

**Comment by gkovacs** [comment]
so the issue was that macos catalina prevented unetbootin from running with new permissions requirements, but it's all now fixed in release 377

**Comment by re4merz** [comment]
one year later, 2 Jan 2021, I'm having this identical problem.  Installs successfully. But on opening this message displays.  Adding password seems to do nothing.  The app appears to be running, but the UI is completely missing.  I've used many times in the past, this has never happened before.
![Screen Shot 2021-01-02 at 14 31 45](https://user-images.githubusercontent.com/12799035/103465165-49036080-4d07-11eb-91eb-81e7874f3379.png)

**Comment by re4merz** [comment]
PS:  Sorry, I'm running Big Sur on an Early 2014 Macbook Air.

**Comment by greenonline** [comment]
I'm getting the osascript dialog on High Sierra 10.13.6. Why is it asking for extra permissions. It is a big put off, and while I want to run and use the application I am not willing to type my credentials in, especially as this application comes from an unverified developer, which already requires explicit permissions to run, in the Security and Privacy control panel.
