### ISSUE TITLE
unebootin not possible to install on KUbuntu 20.04

### ISSUE THREAD

**Issue by GalantGTR** [unetbootin/unetbootin#264]
Следующие пакеты имеют неудовлетворённые зависимости:
 unetbootin : Зависит: libqt4-network (>= 4:4.5.3) но он не может быть установлен
              Зависит: libqtcore4 (>= 4:4.7.0~beta1) но он не может быть установлен
              Зависит: libqtgui4 (>= 4:4.5.3) но он не может быть установлен
              Рекомендует: extlinux но он не будет установлен
              Рекомендует: unetbootin-translations но он не будет установлен
              Рекомендует: gksu но он не может быть установлен или
                                      kdesudo но он не может быть установлен
E: Невозможно исправить ошибки: у вас зафиксированы сломанные пакеты.

You can translate it...but if i cut the translation, than it means that the packages are not possible to install, or all of them to old...so...a problem! how to install it on KUbuntu 20.04???
Thx for Help.

**Comment by amquei** [comment]
The same in Ubuntu Mate 20.04.

**Comment by gRoussac** [comment]
Hi @gkovacs,

Trying to install on a amd64 Debian 5.7.6-1 and could not even libqt4-dev installed, seems qt5 now. 

Is unebottin working on kernel > 5 ? 

Thanks

**Comment by gkovacs** [comment]
Try the PPA at https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa it should work
