### ISSUE TITLE
Showing extremely high amount of data

### ISSUE THREAD

**Issue by djthegr8** [unetbootin/unetbootin#275]
When I was trying to flash Ubuntu 20 on my Win7 laptop using unetbootin, it shows a huge amount of data downloading. Is this accurate?
![image](https://user-images.githubusercontent.com/44142719/91663504-d8ed8f80-eb06-11ea-920c-0ffaeceaa416.png)

**Comment by k12ish** [comment]
This isn't a one off issue either :(
![image](https://user-images.githubusercontent.com/45272873/97106943-87075700-16bc-11eb-93b8-b48da8017316.png)

**Comment by gkovacs** [comment]
This was fixed in the 700 release.
