### ISSUE TITLE
make  install does not work, build does not work, no instructions in your README file on how make it.

### ISSUE THREAD

**Issue by hughbarney** [unetbootin/unetbootin#278]
I tried to use the PPA to install this on Buster.  But kept getting errors when I added the PPA.
In desperation I cloned the sourec code from github.
There is no documentation on how to make this utility or build it.
I guessed there was a script called build but this fails.

Please provide some simple instructions on how to build this.
I expected one of the following might work
 $ make all
 $. /configure
 $ make install

$ cd src/unetbootin
$ ./build
make: *** No rule to make target 'clean'.  Stop.
rm: cannot remove 'Makefile*': No such file or directory
rm: cannot remove 'release/*': No such file or directory
Traceback (most recent call last):
  File "./mkpotfile", line 51, in <module>
    call([qtx11d+'/bin/lupdate', 'unetbootin.pro'])
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
./build-windows: line 25: /home/hughbarney/src/unetbootin/src/unetbootin/qt4-x11/bin/lrelease: No such file or directory
./qmake-windows: 7: ./qmake-windows: /home/hughbarney/src/unetbootin/src/unetbootin/qt4-x11/bin/qmake: not found
make: *** No targets specified and no makefile found.  Stop.
./build-windows: line 28: -strip: command not found
mv: cannot stat 'release/unetbootin.exe': No such file or directory
make: *** No rule to make target 'clean'.  Stop.
./build-linux: line 13: /home/hughbarney/src/unetbootin/src/unetbootin/qt4-x11/bin/lrelease: No such file or directory
./qmake-linux: 6: ./qmake-linux: /home/hughbarney/src/unetbootin/src/unetbootin/qt4-x11/bin/qmake: not found
make: *** No targets specified and no makefile found.  Stop.
./build-linux: line 16: -strip: command not found
mv: cannot stat 'unetbootin': No such file or directory

**Comment by qwertychouskie** [comment]
Probably `cd` into the root level of the cloned directory, then run it as `./src/unetbootin/build`

**Comment by gkovacs** [comment]
The build instructions are at https://github.com/unetbootin/unetbootin/wiki/compile they're linked to from the main website (read the section named "compiling" on https://unetbootin.github.io/ )
