### ISSUE TITLE
Doesn't support macOS version 10.11 or below. Mac: Broken Disk Image .dmg (unetbootin 700)

### ISSUE THREAD

**Issue by Vanylla** [unetbootin/unetbootin#280]
I can not open the disk image "unetbootin-mac-700.dmg" on MacOS 10.11.6
If I try to open it, then an error dialog appears, saying: "no mountable file system".

Maybe unetbootin for MacOS could be distributed in a zip file, as well as in a dmg ?

**Comment by qwertychouskie** [comment]
I've seen this issue before with the Dymo LabelWriter software, I suspect depending on what version of macOS is used to create the DMG it sometimes can't be opened on older macOS versions.

That being said, is there any reason you are still on OSX 10.11.6?  Unless your hardware is 2009 or older, I'd generally recommend running macOS 10.13.x at a minimum.

**Comment by Vanylla** [comment]
Does unetbootin 7.00 run on MacOS 10.11 ? 
If it really runs on MacOS 10.11, then it would be good, if it would be distributed in a file format which can be opened in MacOS 10.11 (e.g. in a zip file or compatible dmg file).

---

I am still on MacOS 10.11.6 because, in general, it runs well, the software I use runs well on it and it works well with the peripherals I use.

**Comment by cupcake99** [comment]
I just downloaded and am having the same problem. I'm still on El Capitan (10.11.6) as well. Have had the same issue before when trying to open dmg files created from later APFS versions of OSX. It's really annoying that the software might work on the OS, but the distribution format prevents it being opened. I also cannot see how a dmg is in any way better than a zip file to package an executable.

**Comment by gkovacs** [comment]
unetbootin 700 upgraded to Qt 5.12, which doesn't support versions of macos below 10.13 (had to upgrade to it for support for dark mode, among other things). Yes v661 supports ancient versions of macOS (though not Catalina and above).

**Comment by cupcake99** [comment]
> unetbootin 700 upgraded to Qt 5.12, which doesn't support versions of macos below 10.12

Ah, that explains it. Thanks. Maybe this info could be put in the docs somewhere?

**Comment by gkovacs** [comment]
I've added it to the release notes at https://github.com/unetbootin/unetbootin/releases/tag/700
