### ISSUE TITLE
unetbootin failing to launch on MacOS 11.1 Big Sur (Apple Silicon M1)

### ISSUE THREAD

**Issue by ssuds** [unetbootin/unetbootin#284]
-Downloaded latest DMG (unetbootin-mac-700.dmg)
-Get popup that 'osascript wants to make changes.'
-Unetbootin logo shows up on dock
-No GUI shows up

<img width="273" alt="Screen Shot 2020-12-16 at 3 25 34 PM" src="https://user-images.githubusercontent.com/10721344/102418653-04f82800-3fb3-11eb-8eed-eca646b57c8e.png">

<img width="260" alt="Screen Shot 2020-12-16 at 3 26 35 PM" src="https://user-images.githubusercontent.com/10721344/102418698-1ccfac00-3fb3-11eb-80d2-025b0b8a6e9b.png">

**Comment by gkovacs** [comment]
Thanks for the report! Sounds like this might be an issue in Rosetta (Apple's emulation environment for running Intel apps on Apple Silicon). I don't have any Mac machines with Apple Silicon processors available to me at the moment unfortunately, but will definitely look into this once I have access to one.

**Comment by timgjr** [comment]
I'm on Big Sur with **_Intel_** and have same exact issue. I suspect it's a security issue with Big Sur in general.. I keep having to authenticate every time I run it.. which is odd..

**Comment by coderite** [comment]
This is reproducible on my Mid 2014 Mac with Mac OS Big Sur 11.1

<img width="297" alt="Screen Shot 2020-12-19 at 8 00 57 PM" src="https://user-images.githubusercontent.com/4528272/102697268-e903b900-4234-11eb-8639-1c7abc75ce24.png">

**Comment by riegelstamm** [comment]
For those having this problem, does it occur with an admin user or normal user? If the latter, try running the app as an admin user. When running as normal user on Catalina, I get a window with "UNetbootin needs permissions to write to your USB drive. Type your password to allow this." It appears that it assumes the user has admin privileges (even though it should not). Admin privileges are required to give access to the USB drive.
![image](https://user-images.githubusercontent.com/10802064/102925608-4e37f400-4459-11eb-97af-abe83732e6db.png)

**Comment by coderite** [comment]
It happens when launching the app as a regular user from the UI. However, If I sudo launch it like an admin from the terminal, it works.

<img width="400" alt="Screen Shot 2020-12-22 at 8 35 01 PM" src="https://user-images.githubusercontent.com/4528272/102926610-9d037f00-4495-11eb-9dde-8a47bf33d9ac.png">

**Comment by riegelstamm** [comment]
@coderite Exactly. You need to be an admin in order to grant UNetbootin permission to the USB drive. It's a design flaw in the UI. See this for more info: https://github.com/unetbootin/unetbootin/issues/286

**Comment by ssuds** [comment]
Strange, I'm getting this error when trying to Sudo open unetbootin:

% sudo open unetbootin.app

The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x14be36b50 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x14be38150 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}

**Comment by riegelstamm** [comment]
@ssuds This method works for me:

`$ su admin`
`Password:`
`$ /Applications/unetbootin.app/Contents/MacOS/unetbootin`

Replace "admin" with your admin user name

**Comment by ssuds** [comment]
@riegelstamm , no dice unfortunately. 
<img width="1013" alt="Screen Shot 2020-12-22 at 12 32 15 PM" src="https://user-images.githubusercontent.com/10721344/102931254-e7afd780-4452-11eb-9a9a-c919eacae91a.png">

When I force quit, I get the following message, unsure if it's useful for debugging in any way:
`execution error: PasteBoard: Error creatPasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960] (1009)`

**Comment by riegelstamm** [comment]
The only other thing I can think of is to actually switch to the admin user and try to run it from there. If the GUI still doesn't load after entering the password, then there's definitely a problem on Big Sur.

**Comment by mhv75** [comment]
I logged in as admin, exact problem as ssuds

**Comment by Kreeblah** [comment]
I'm seeing the same issue (also on Intel, on Big Sur 11.1) when I try to run it from the app bundle, regardless of whether I'm running it as my user or as root.  Either way, the UI doesn't show up.

However, if I use the terminal to navigate into the app bundle, into Contents/MacOS, and use sudo to run the unetbootin binary in there, the UI shows up just fine.

**Comment by Zarickan** [comment]
UI doesn't show up for me, on Big Sur 11.2 beta. Same thing regardless of whether I run the app directly or from the terminal with sudo.

**Comment by NuclearMonster** [comment]
On intel Big Sur 11.1 I was able to launch from the command line using sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin

**Comment by twogee** [comment]
Intel Big Sur is just like Catalina ("Failed to set up CFPasteboardRef ... Connection invalid"). Only there are several pasteboards: general, find, DefaultAsciiKeyboardLayoutPasteboard, ApplePerContextInputPasteboard, AppleIntlFileCacheModificationDatePasteboard?

**Comment by gkovacs** [comment]
macOS Big Sur issue has been fixed in release 702.

**Comment by Galzk** [comment]
Running M1 with 11.2.3 (20D91) still had that issue,
I had to run it with sudo to get it to work

**Comment by DScottHolmes** [comment]
The following worked for me. The key was dragging the file into the terminal window to get the proper path, which on my machine was:
/Volumes/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin

=====
1. Download UNetbootin from the official website and double-click to mount the package.
2. Copy the mounted file to any folder inside your Mac, a commonplace is the Applications folder.
3. Right-click on unetbootin and click Show package contents.
4. Go to contents > MacOS. Press Command + Space and write terminal. Press enter and it’ll launch a terminal window.
5. Write sudo and drag unetbootin shown inside MacOS folder into the terminal window.
6. Hit enter and it’ll ask your system password. Enter the password and hit enter. This time UNetbootin will run without any permission error.

Solution found at:
https://www.talkofweb.com/troubleshoot-unetbootin-permission-issue-in-catalina-and-big-sur/

**Comment by roelzkie15** [comment]
Has anyone encountered this issue on the M1 Macbook? I have a Big Sur 11.0.1

<img width="507" alt="Screen Shot 2022-02-03 at 2 36 54 PM" src="https://user-images.githubusercontent.com/20513403/152293536-b26fec45-3342-45d9-8b09-899f74ab9d26.png">

**Comment by Eduar2TC** [comment]
run sudo /Volumes/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin

**Comment by Ch0p5h0p** [comment]
It's a bit late, but if anyone's still having this issue, I fixed it like this:
```
$ su admin
Password:
$ sudo chmod a+x unetbootin
```
This way, you can run it from non-admin as well if you need to.
