### ISSUE TITLE
Osascript wants to make changes -Mac OS Big Sur

### ISSUE THREAD

**Issue by re4merz** [unetbootin/unetbootin#287]
on app launch, this message appears and seeks the users password.  the app appears in the menu bar, but does not launch the UI.  Just tried deepin.  Same thing occurs.

**Comment by web-engineer** [comment]
same problem here - only way to quit is from the top menu bar, force quit also doesnt work.

Tried giving full disk access but no beans either.

**Comment by AjaxOdessa** [comment]
I was able to get around this problem by starting application from Terminal with elevated permissions eg. `sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin` Still it doesn't always work, but at least 4 of 5 attempts it starts properly.

**Comment by web-engineer** [comment]
Switched to [balenaetcher](https://www.balena.io/etcher/) for now, hope they sort this out at this was my goto tool and has served me well.

**Comment by re4merz** [comment]
> I was able to get around this problem by starting application from Terminal with elevated permissions eg. `sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin` Still it doesn't always work, but at least 4 of 5 attempts it starts properly.

Yes, that worked for me.  Thanks.

**Comment by gkovacs** [comment]
macOS Big Sur issue has been fixed in release 702.
