### ISSUE TITLE
process stopped

### ISSUE THREAD

**Issue by kees-popinga** [unetbootin/unetbootin#290]
Hi, im using unetbootin-windows-**700**.exe.
I downloaded a kubuntu .iso and i am trying to create a bootable usb but the process crashes almost immediately.
You can see the situation here; the same thing on different PC (windows 10).

![Immagine 2021-02-02 104152](https://user-images.githubusercontent.com/78412997/106581751-83992c80-6543-11eb-98fe-402603d59ff0.png)

I have on old version (unetbootin-windows-**661**.exe) and this works fine.
Thanks

**Comment by gkovacs** [comment]
It didn't crashed. It's extracting files. Just wait for it to finish running.
