### ISSUE TITLE
[website https://unetbootin.github.io/] Badware risk for lubuntu [dot] net according to uBlock Origin.

### ISSUE THREAD

**Issue by vuod** [unetbootin/unetbootin#321]
On the website https://unetbootin.github.io/ in the section _Supported Distributions_ the link for Lubuntu should be https://lubuntu.me and not lubuntu [dot] net.

https://ubuntu.com/download/flavours links the https://lubuntu.me website.

lubuntu [dot] net is in _uBlock filters – Badware risks_

Source : 
https://github.com/uBlockOrigin/uAssets/issues/9785

**Comment by gkovacs** [comment]
Thanks for the notification, I have updated the link to lubuntu.me
