### ISSUE TITLE
MacOS BigSur - Cannot select USB device in GUI

### ISSUE THREAD

**Issue by chris-zenfolio** [unetbootin/unetbootin#322]
I installed UNetbootin using HomeBrew and it is unable to select any USB device, mounted or unmounted.  My USB drive is on /dev/disk2 and, after the successfully completing the permissions prompt to access the removable media (as seen in other issue tickets), I cannot select the USB device.  I ran "brew update" and "brew upgrade" during the troubleshooting process with no change in results.

I reviewed the other issues related to MacOS and tried some of those methods to launch UNetbootin, but none of them resolved this apparent permissions problem.  I'm back to using DD to write the ISO to my USB drive.

Edit:  Added brew update/upgrade info

**Comment by maichai** [comment]
have you formatted the pen drive as MS FAT with MBR ?

**Comment by chris-zenfolio** [comment]
Closing this issue because I never saw the reply (sorry, notifications didn't work right) and there's no need to keep open a 2 year-old issue with no apparent activity (by me or anyone else)
