### ISSUE TITLE
Is the project officially abandoned?

### ISSUE THREAD

**Issue by qwertychouskie** [unetbootin/unetbootin#348]
Only 1 commit has been made in the past 1 and a half years.  New bug reports keep stacking up, with no action from @gkovacs to move things forwards.  If they are not able to maintain the project anymore, that's totally fine (life happens), but either a call to action should be put out in the relevant forums to find a new maintainer, or the project's readme and website should be updated to inform users of the project state and refer them to an actively developed project (e.g. Etcher).

I'll put out an offer to at least help with managing incoming issue reports and website updates (I revamped the website a few years ago, so I'm familiar with that part at least), but I'm not super familiar with the code-base so I wouldn't be able to offer more than perhaps the occasional small tweak/bugfix.

**Comment by gkovacs** [comment]
Not abandoned, just a bit busy with life and haven't had time to follow up on the various bug reports as the program is working fine for me and I haven't been able to reproduce them. I'll make updates when I have time.

**Comment by qwertychouskie** [comment]
@gkovacs Good to hear things are still alive.  I'd still recommend putting out a call for potential additional maintainers, as having only one person working in any project means a single point of failure.  Even just getting a bit of extra help triaging issues, closing duplicates, etc would be beneficial to the project (which I'm totally willing to help with if wanted).
