### ISSUE TITLE
QT4 discontinued

### ISSUE THREAD

**Issue by flleeppyy** [unetbootin/unetbootin#355]
QT4 is discontinued, and most users on latest distros cannot install unetbootin because the repositories have removed QT4. Please consider QT5 or something similar.

**Comment by gkovacs** [comment]
All releases starting with 700 are already using QT5, the switchover happened back in 2020 with this PR https://github.com/unetbootin/unetbootin/pull/137 this is just an issue with the package maintainer for your distribution not having updated the package.
