### ISSUE TITLE
Is unetbootin.fr a scam ?

### ISSUE THREAD

**Issue by ghost** [unetbootin/unetbootin#373]
Hello,
The website is a way to install Unetbootin but the mac version don't work and keep asking my password and i discovered that on the original website https://unetbootin.github.io/ that work. Did I install a virus ?
Sorry for my english.

**Comment by Pachuquero** [comment]
At least VirusTotal.com [finds 4 out of 72](https://www.virustotal.com/gui/file/65ba5ff090be1cc96dec40509c9002582f4663634cb63b311941321907701483).
