### ISSUE TITLE
Missing ubnldr.mbr when booting

### ISSUE THREAD

**Issue by Vercixx** [unetbootin/unetbootin#374]
When trying to boot into GParted LiveCD installed on hard drive, it shows an error
![image](https://github.com/unetbootin/unetbootin/assets/112702555/ca12b67a-e6ea-480e-9bf8-67ef2189f421)

**Comment by ZainA-Official** [comment]
https://github.com/unetbootin/unetbootin/issues/338

**Comment by baqlias** [comment]
I am trying to install Linux Mint on my Windows 11 tablet.  It's a Raytrek tablet with an Intel Celeron N4000 CPU, 8 gb of RAM and 128 GB of internal storage. When I try the Live CD method, the tablet will not boot into the USB stick, even when I use boot override. Either my tablet freezes as it begins booting, or it boots Windows, even when I change the boot order to make the Live CD first. This was true for other software I have tried, such as Ventoy. Secure boot is disabled in BIOS. There is no option for Legacy mode in this BIOS. When I try to install using unetbootin's hard disk mode, I get the error above. I haven' been able (yet) to find out how to update this BIOS, or if that is even possible. Can I install a Linux distribution on this tablet, or should I just give up? Thanks for any advice you can offer!
