### ISSUE TITLE
Windows Download Link Broken

### ISSUE THREAD

**Issue by HaBaLeS** [unetbootin/unetbootin#51]
http://launchpad.net/unetbootin/trunk/613/+download/unetbootin-windows-613.exe Ist not working at the moment. Stalls after 400k then times out. 

Maybe a Launchpad Issue maybe corrupted upload.

**Comment by gkovacs** [comment]
Launchpad seems to be having some issues with their servers right now, try
the downloads on sourceforge for now
http://sourceforge.net/projects/unetbootin/files/?source=navbar
