### ISSUE TITLE
Support for Qt5

### ISSUE THREAD

**Issue by sl1pkn07** [unetbootin/unetbootin#53]
Hi (and happy new year)

Any plans to support build unetbootin with Qt5 frameworks?

greetings

**Comment by gkovacs** [comment]
I believe it would break compatibility with some older OSes and increase the download size, and there aren't any new features in Qt5 that seem very useful for this project, so probably just sticking with Qt4 for the time being.

**Comment by sl1pkn07** [comment]
Qt4 leads unsuported and deprecated in near future(or now) like Qt3

http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/

is time to migrate

greetings

**Comment by Arnaudv6** [comment]
> Qt 4.8.7 is planned to be the last patch release of the Qt 4 series. Standard support is available until December 2015, after which extended support will be available. We recommend all active projects to migrate to Qt 5, as new operating systems and compilers with Qt 4.8 will not be supported.


[Official source](http://blog.qt.io/blog/2015/05/26/qt-4-8-7-released/)
Time to migrate indeed.
Though I sincerely hope Qt stays with this API and major version for the decades to come.

**Comment by ahjolinna** [comment]
really, still no Qt5 version? it's 2017?! ...or are we waiting for Qt6? which arrives next year -_-

**Comment by Chemrat** [comment]
I'm looking into unetbootin code and there's really only one thing preventing it from porting to Qt5 easily, there is no support for FTP LIST command in Qt5: https://bugreports.qt.io/browse/QTBUG-26294

I've actually re-writtent the rest with QNetworkAccessManager (recommended replacement for QFtp and QHttp) and this is probably the only real problem, if that is solved I can make a pull request with Qt5 port

Possible solutions:
1. Pull in https://github.com/qt/qtftp as a submodule because almost no other distro ships it
2. Use some other, more popular FTP library for specifically getting FTP lists
3. Implement FTP LIST with some other Qt classes inside Unetbootin
4. (temporary) ditch support for download locations that require FTP listing

I don't see any real problem with the last option, to be honest. It seems that it would affect only Dr. Web downloads, but it seems that their FTP is now closed to public access anyways.

**Comment by tsimonq2** [comment]
Bump, Debian plans on removing Qt 4 in the Buster cycle, and Ubuntu around the same time that Debian does.

**Comment by chainria** [comment]
Actually, I just had to throw unetbootin from all my Gentoo systems. It was the last package requiring all of Qt4.

**Comment by qwertychouskie** [comment]
@chainria It seems Gentoo is now carrying the patch (https://github.com/gentoo/gentoo/commit/24d7224ac9e01b3da45520f9204d4d4393f5cb4b) so you can re-install it. :)  Though this still needs to be fixed upstream (here).

**Comment by chainria** [comment]
@qwertychouskie Thanks for pointing me to this. It works like a charm. And very light dependencies!

**Comment by fcladera** [comment]
Arch dropped support for qt4
https://www.archlinux.org/packages/extra/x86_64/qt4/

**Comment by mbrennr** [comment]
> Arch dropped support for qt4
> https://www.archlinux.org/packages/extra/x86_64/qt4/


There is a package in the AUR. 
https://aur.archlinux.org/packages/qt4/
Build time is 69 SBU according to Linux from Scratch.
http://www.linuxfromscratch.org/~thomasp/blfs-book-xsl/x/qt4.html

**Comment by FalcoGer** [comment]
Ubuntu dropped QT4 from the repositories with focal. It's about time this gets ported.

**Comment by adrianinsaval** [comment]
Any progress on this front?

**Comment by leggiero** [comment]
Would be really good if the change to Q5 happens. Unfortunately I can use UNetbootin in Ubuntu 20.04 due the QT4 drop.

**Comment by gardenappl** [comment]
For Arch Linux users, I created an AUR package with the fork by @Chemrat: https://aur.archlinux.org/packages/unetbootin-qt5-git/

It's not perfect but works well enough at the moment.

**Comment by TheCompGeek** [comment]
Qt4 is dead in Debian Testing. Just had Tuxboot ripped out from under me. Tuxboot is long-dead upstream and it seems that the dev's gone radio silent. Kind of a 3-way pull between dd and manually installing a bootloader on my USB drive every time I want to change what boots up from it, using a machine that still has a working Tuxboot install, or this.

It's time to finish up this port and get it out the door.

**Comment by PatrickVerner** [comment]
> For Arch Linux users, I created an AUR package with the fork by @Chemrat: https://aur.archlinux.org/packages/unetbootin-qt5-git/
> 
> It's not perfect but works well enough at the moment.

Can you post a generic source package so I can use this in slackware-current?

**Comment by gkovacs** [comment]
FYI, have finally gotten the last remaining Qt5-related bugs fixed and release 700 is now based on qt5. @PatrickVerner tarball can be found at http://unetbootin.sourceforge.net/unetbootin-source-latest.tar.gz see https://github.com/unetbootin/unetbootin/wiki/compile for compilation instructions.
