### ISSUE TITLE
are admin rights really required?

### ISSUE THREAD

**Issue by ousia** [unetbootin/unetbootin#57]
@gkovacs, sorry if the question is stupid (I cannot code), but the answer is very relevant for me.

Is it really necessary that unetbootin should have admin rights to write an USB file?

In Linux, admin rights seem to be mandatory to run the program.

Would it be possible to make this optional?

**Comment by gkovacs** [comment]
Yes they are necessary. The program has to write a bootloader to the USB drive which you can't do without admin rights.

**Comment by ousia** [comment]
@gkovacs, many thanks for your reply.
