### ISSUE TITLE
ubuntu 16.10 xserver bad access

### ISSUE THREAD

**Issue by c3ph3us** [unetbootin/unetbootin#66]
installing from ubuntu repo on 16.10 (ubuntu/gnome)
start via launcher with sudo password provided results in blank(white) gui screen 
start from xterm via sudo result in:

X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x145
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0xfe
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x1a00010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x1a00010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x1a00010

**Comment by gkovacs** [comment]
according to https://bugs.archlinux.org/task/42030?project=5 this seems to be due to new security policies, a temporary workaround is to run it with

sudo QT_X11_NO_MITSHM=1 unetbootin

I will try to fix the package soon

**Comment by gkovacs** [comment]
latest version in my ppa (625) should fix this https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa please reopen if you still have the issue

**Comment by gutigen** [comment]
Using 625 on Arch and I still have this issue. Above workaround doesn't work, other Qt4 and Qt5 apps are fine.

Strace:
https://gist.github.com/gutigen/688ef0dd6b4b70abd2b4217b46bc8267

**Comment by ndxf** [comment]
`sudo QT_X11_NO_MITSHM=1 unetbootin`

this seems to have fixed the problem for me.

**Comment by vageliskatsiotis** [comment]
Using 625-1 on Arch. ndxf's answer does not work for me. Any ideas?

**Comment by zygimantus** [comment]
Yep, ArchLinux still fails while running Unetbootin.

**Comment by vadixidav** [comment]
Arch linux not working here either.

Getting this: https://gist.github.com/vadixidav/afc0f9ebd5ebb7ebb1f321e7f7108c14

**Comment by freakyuser-osm** [comment]
I just updated my Ubuntu Gnome from 16.04 to 16.10 and got the error.

The workaround works though...

Would be nice to have the package fixed :)

(Btw., how can I reopen this?)

**Comment by nouvieux** [comment]
For the arch users, this may be caused by running X as a standard user, see https://wiki.archlinux.org/index.php/xorg#Rootless_Xorg_.28v1.16.29. I installed xorg-xwrapper from the AUR and that fixed my issue with unetbootin-625 on X-1.18.

**Comment by sl1pkn07** [comment]
tnx @nouvieux !!

**Comment by Glasairman** [comment]
Still happening in 2018 (Zorin 12.3) and Kernel 4.13.0-39

david@david-linux:~$ gksudo  unetbootin  /dev/sdd1
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x260000f
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2600010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2600010
