### ISSUE TITLE
won't start 16.04 lts

### ISSUE THREAD

**Issue by 0usssama** [unetbootin/unetbootin#67]
i'm on gnome-ubuntu 16.04LTS 
when i launch  unetbootin i got no GUI only the frame and the title and this : 

X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0xbd
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2400010

**Comment by 0usssama** [comment]
when i run this command:   "sudo QT_X11_NO_MITSHM=1 unetbootin" it works !!

**Comment by gkovacs** [comment]
latest version in my ppa (625) should fix this (it adds the QT_X11_NO_MITSHM=1 to the launch command) https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa please reopen if you still have the issue

**Comment by jollyrogers88** [comment]
still not working for me (even with QT_X11_NO_MITSHM=1)

**Comment by rubo77** [comment]
1. under user run

        xhost local:root
    non-network local connections being added to access control list

2. then with sudo

        sudo QT_X11_NO_MITSHM=1 /usr/bin/unetbootin 

Source: https://github.com/unetbootin/unetbootin/issues/94
