### ISSUE TITLE
Xenial packages are missing in the PPA

### ISSUE THREAD

**Issue by Konstamokh** [unetbootin/unetbootin#68]
I'm only getting version 608, instead of 613 and I suspect it's because I'm running 16.04.

**Comment by shivarajnaidu** [comment]
this is same as issues #66 and #67  . guys please soon update unetbootin ppa for Ubuntu 16.04 LTS

**Comment by gkovacs** [comment]
ppa has been updated for xenial https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa with latest version (625)
