### ISSUE TITLE
Black screen after clicking on "Start Kubuntu" or other options

### ISSUE THREAD

**Issue by Konstamokh** [unetbootin/unetbootin#69]
I can create the stick just fine and even get to the menu where I can select "Start Kubuntu", but after that nothing happens. I'm using the 16.04 64bit image from their website.

**Comment by gkovacs** [comment]
this is most likely an issue with kubuntu not being compatible with your hardware (most likely your graphics card) rather than an issue with unetbootin. you should probably check ubuntuforums to see if they have tips
