### ISSUE TITLE
please update your official ppa for Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by shivarajnaidu** [unetbootin/unetbootin#70]
this is same as issues #66 and #67 and #68 . guys please soon update unetbootin ppa for Ubuntu 16.04 LTS
@unetbootin

**Comment by gkovacs** [comment]
ok updated for xenial! enjoy. https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa

**Comment by shivarajnaidu** [comment]
:+1:  thank you very much.. @gkovacs 
It's LTS release.. Going to be a star for next 5 years . so it's important to support every piece of software ...  :blush:
