### ISSUE TITLE
625 Mac Release does not include Qt Library

### ISSUE THREAD

**Issue by joel-wright** [unetbootin/unetbootin#72]
The 625 release downloadable zip for mac contains an application that cannot run because the Qt libraries cannot be found at

    /usr/local/Trolltech/qt-4.8.7/lib

**Comment by gkovacs** [comment]
thank you very much for catching this! I have removed the faulty mac binary and have reverted the default release back to 613 until I have a fixed and fully-tested binary. should probably have tested on a fresh install before releasing. (the qt library is actually bundled in that unetbootin.app but the library load paths were not correctly updated to use the built-in one). thanks again!

**Comment by gkovacs** [comment]
I have fixed this issue in this updated release ( https://launchpad.net/unetbootin/trunk/625/+download/unetbootin-mac-625.dmg ), haven't yet made it the default download as I'm waiting for some more testing feedback, let me know whether it works!

**Comment by joel-wright** [comment]
Thanks - the new default download of 625 is now a dmg and starts for me now.
