### ISSUE TITLE
Crashes on startup on Mac OS 10.6.8

### ISSUE THREAD

**Issue by programmingkidx** [unetbootin/unetbootin#73]
When I try to run this program, it always crashes. Here is some info that might help.

Crashes on Mac OS 10.6.8

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x0000000000000000
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   ???                             0000000000 0 + 0
1   QtGui                           0x001cc4c1 qt_mac_update_os_settings() + 2321
2   QtGui                           0x001cebc8 qt_init(QApplicationPrivate_, int) + 2072
3   QtGui                           0x002422e1 QApplicationPrivate::construct() + 225
4   QtGui                           0x00242626 QApplication::QApplication(int&, char__, bool, int) + 102
5   QtGui                           0x00242692 QApplication::QApplication(int&, char_*, bool, int) + 50
6   com.yourcompany.unetbootin      0x000057ca main + 74
7   com.yourcompany.unetbootin      0x0000337d _start + 212
8   com.yourcompany.unetbootin      0x000032a8 start + 40

I do not have qt installed on my computer.

**Comment by gkovacs** [comment]
thanks for the report! do you encounter the same issue with the 613 release? [that was built using a different version of qt] https://launchpad.net/unetbootin/trunk/613/+download/unetbootin-mac-613.zip

**Comment by frickler01** [comment]
Can reproduce. The 613 release starts normally.

**Comment by cobwebid** [comment]
Affirmed, 625 crashes on Snow Leopard, 613 works.

**Comment by Brainzyy** [comment]
@gkovacs Could you make a new release so that we can use 625 on Snow Leopard and Lion? I'm not sure if my old macbook can handle building this.

**Comment by Brainzyy** [comment]
@gkovacs I can't build on Mac OS X Lion. The qt4 files you distribute on the wiki page about building were built for the i386 architecture and the architecture for more modern Mac systems is x86_64. I get errors about the i386 thing. is there any way you could fix this?

**Comment by mokshakira** [comment]
ok 613 version runs on my snow leopard but doesnt find mi usb stick.
searching for oter options but its not easy with mac os 10.6
anyone knows how i can make a live usb to get out of tis shity snow leopard?
(my diskdrive is broken)

**Comment by sjc314** [comment]
I had the same problem, ie version 625 crashes and 613 can't find the usb stick.  The stick was formatted as MacOS Extended.  Once I reformatted it to MS Dos Fat 32, it found it.  Unfortunately when it finished the installation gave me a message to the effect that it wouldn't boot on a Mac.

**Comment by gkovacs** [comment]
@sjc314 ignore the message 613 gives you that it can't boot on a mac, for many distributions (ie, recent versions of ubuntu) it will actually boot on mac fine in spite of the message

**Comment by sjc314** [comment]
@gkovacs Thanks!  You are right.  It did boot.  But it just hangs on "Try Out" or "Install"  I haven't been able to get the disk image it to install in Parallels Desktop either.  Going to try to upgrade to Parallels 9.

**Comment by gverm** [comment]
This should be fixed now too, right @gkovacs ?

**Comment by gkovacs** [comment]
Correct, should be fixed as of release 638 (that one should be able to run on 10.5 and above)
