### ISSUE TITLE
USB wireless mouse and keyboard not working

### ISSUE THREAD

**Issue by cganthony** [unetbootin/unetbootin#77]
Trying to install Android 6.0 on my PC. The installation option shows the different partitions available on my system. But unable to scroll down the list using the mouse or the keyboard. Looks like it just hangs there. Have to reboot the system using the power button on the PC.

**Comment by gkovacs** [comment]
This is an issue with whatever distribution of android that you are trying to install, not unetbootin. Report it to them.
