### ISSUE TITLE
Extraction phase stalls

### ISSUE THREAD

**Issue by rtindell** [unetbootin/unetbootin#84]
When in the Extracting and Copying Files (Current) step, the progress bar hits a point and makes no further apparent progress.  The first time I tried, it hit a bottleneck at 10 of 452 files.  I eventually stopped it with ctrl-c and started again.  This time it stopped making progress at 253 of 452 files.  I am trying to create a Live USB for Ubuntu.

**Comment by qwertychouskie** [comment]
If the file is "filesystem.squashfs" or something similar, it is normal for it to take much longer here, as this file takes up most of the space, so it takes longer to transfer.

**Comment by rtindell** [comment]
I believe that may have been the case.  It is chugging along now and is up to 230 of the 452 files.  If it stalls at squashfs, I'll just be patient.  Thanks for the advice.
