### ISSUE TITLE
Not bootable USB - "Missing Operating System" error message

### ISSUE THREAD

**Issue by BelladonnavGF** [unetbootin/unetbootin#90]
I'd like to share here an issue I encountered while making a liveUSB with unetbootin. Since I found the solution myself later, I like to share it here, so it can help others potentially.

**VERSION:** seen with unetbootin 608 and unetbootin 625, but not 585.

**ISSUE:** I attempted to make a liveUSB with unetbootin. However, upon (re)boot, the liveUSB refused to boot, and boot commenced into the "regular" OS after flashing the message "Missing Operating System".
This happened with liveUSBs made for various OS's (xubuntu, lubuntu, Mint, MATE, debian jessie, kali), and with unetbootin versions 602 and 625. The created liveUSBs failed to boot on multiple boxes. Reformatting and creating new partition tables did not improve the situation (although it did give a clean start of course), not did using different USB drives.

However, when a liveUSB was created of the same .iso with unetbootin version 585, a perfect, bootable liveUSB was created on the previously failing USB stick. In my findings, this contradicts community advice (found after Googling) that "the type" or "the brand" of USB jump drive might matter.

**SOLUTION:** After some research, all versions of unetbootin turned out to make perfect, bootable liveUSBs of all tried OS's on various USB sticks of varying size and make.
The **liveUSBs made with unetbootin versions 608 and 625 did need additional action however**;
After creating the liveUSB with unetbootin, **add a boot flag** to the FAT32 partition on the USB stick (I did this with GParted). Reboot with the liveUSB will now give the grub menu.

Finally, a big thanks to the devs and maintainers of unetbootin!

**Comment by qwertychouskie** [comment]
I don't think this should be closed, Unetbootin _should_ add the boot flag automatically, as v585 did.

**Comment by genterminl** [comment]
I just ran into this problem with unetbootin 625 and slackware64-live-14.2.iso.  I'll have to try again to confirm, but my first attempt at manually setting the partition to bootable did NOT make any difference.  (I also had the same problem using Slack's iso2usb.sh script, but I doubt that has any relevance to the unetbooting problem.)  Simply dd'ing the iso to the USB booted fine.  I'm on Gentoo, and 625 is the most recent version available - I'll have to see if I can prompt them to upgrade.

**Comment by BelladonnavGF** [comment]
#112

**Comment by evbo** [comment]
I too am having this issue as a first time user of Unetbootin. GParted is a linux only tool, and I only have windows so I'm not sure how to fix this issue (if it is in fact the boot flag not set correctly).

Steps to reproduce:

*  Used windows to format my USB 2.0 with: 974 MB capacity, FAT32 fs, and 4096 bytes allocation size (quick format)
*  Downloaded unetbootin-windows-657.exe
*  Selected Puppy Linux and hit OK
*  Restarted my machine and selected to boot from usb
*  Got error: "Missing Operating System"

**Comment by mperdikeas** [comment]
Encountered this with UNetbootin version 608-1. Fixed it (as advised) with:

    parted /dev/sdb set 1 boot on

**Comment by tomachinz** [comment]
Me too, spent days cloning various distros, Lubuntu, Ubuntu, CoreOS, always I see "Missing Operating System"! No idea what to do. Will try those ideas....
